In [1]:
import numpy as np

def step_function(x):
    return np.array(x>0, dtype = np.int)

# 계단 함수, bool 배열을 만든 후 data type을 np.int로 바꿔서 반환


In [2]:
import numpy as np

# 바이트 데이터
data = b'\x01\x02\x03\x04'

# 데이터를 int 타입의 NumPy 배열로 변환
array = np.frombuffer(data, dtype=np.uint8)

print(array)


[1 2 3 4]


In [3]:
import pickle
# pickle.dump() 객체를 pickle 파일로 mnist.py에 있음

with open("./mnist.pkl", 'rb') as f:
    data = pickle.load(f) # picle 파일에서 다시 객체로 불러오기 

print(data)    

{'train_img': array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), 'train_label': array([5, 0, 4, ..., 5, 6, 8], dtype=uint8), 'test_img': array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), 'test_label': array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)}


In [4]:
import os, sys

os.getcwd()

'c:\\Users\\junun\\OneDrive\\document\\deepfish'

In [5]:
import pickle

with open("./sample_weight.pkl", 'rb') as f:
    data = pickle.load(f)

print(data['W1'].shape)

print(data['W2'].shape)

print(data['W3'].shape)


# predict의 구조를 상상하기 위해 shape해서 봤습니다

(784, 50)
(50, 100)
(100, 10)


In [6]:
x = [0,12,2,3,4,5]

for i in range(len(x)):
    print(i)

0
1
2
3
4
5


In [7]:
import numpy as np
import pickle
import tensorflow as tf

def get_data():
    mnist = tf.keras.datasets.mnist
    (x_train, t_train), (x_test, t_test) = mnist.load_data()
    return x_test, t_test

x, t = get_data()
x = x.reshape(-1,784) # ndim =1 이 784가 되고 ndim = 0는 자동으로 하게 만들어줌
print(f'x shape: {x.shape}')
print(f't shape: {t.shape}')

print(f'len x: {len(x)}')
print(f'len x[0]: {len(x[0])}')
print(f'len x[1]: {len(x[1])}')
def sigmoid(x):
    return 1/(1+np.exp(-x))

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))  # axis=1로 각 행의 최대값을 사용
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)  # sum도 axis=1로 설정



def init_network():
    with open("./sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)
    return network

network = init_network()

def predict(network, x):
    w1, w2, w3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, w1) + b1
    print(f'a1: {a1.shape}')
    z1 = sigmoid(a1)

    print(f'z1: {z1.shape}')
    a2 = np.dot(z1, w2) + b2
    
 
    print(f'a2: {a2.shape}')

    z2 = sigmoid(a2)

    
    print(f'z2: {z2.shape}')

    a3 = np.dot(z2, w3) + b3
    print(a3.shape)
    y = softmax(a3)
    print(f'y: {y}')
    return y


print(type(predict(network, x)))

x shape: (10000, 784)
t shape: (10000,)
len x: 10000
len x[0]: 784
len x[1]: 784
a1: (10000, 50)
z1: (10000, 50)
a2: (10000, 100)
z2: (10000, 100)
(10000, 10)
y: [[4.2878964e-06 4.5729229e-07 1.8486247e-04 ... 9.9919468e-01
  3.8066861e-07 5.3082942e-04]
 [3.6033173e-04 1.1461673e-03 9.8586720e-01 ... 2.6647373e-07
  2.8627031e-04 4.1333039e-09]
 [1.3850805e-11 9.9969125e-01 1.2972941e-04 ... 3.0878166e-06
  1.1507778e-04 3.6269168e-07]
 ...
 [3.1500335e-08 3.2843438e-06 1.0989393e-05 ... 3.9859158e-05
  6.1727711e-04 3.9078239e-03]
 [6.0160214e-04 2.1150883e-04 7.0512651e-05 ... 1.8556637e-05
  5.5061156e-01 1.5017099e-04]
 [7.1861854e-05 6.9937238e-07 4.3266578e-04 ... 1.2828664e-07
  9.9584452e-07 3.4977271e-07]]
<class 'numpy.ndarray'>


C:\Users\junun\AppData\Local\Temp\ipykernel_16756\3098911386.py:19: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [8]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
t.shape

(10000,)

In [10]:
print(min(t))

0


# 정규화
- 0~1 사이의 범위 안의 값으로 만드는 것 
- x - min(x)/ max(x) - min(x)

# 배치

- 데이터셋을 묶음으로 처리하는 것
- 배치를 하면 연산속도가 빨라진다 (하드웨어(gpu)의 병렬처리 능력 사용, 메모리에 i/o의 대기시간을 줄이고 데이터를 미리 로드할 수있고 연산 중에 cpu나 gpu를 연속적으로 수행할 수 있기 때문)


In [26]:
import numpy as np

p = np.array([1, 2, 3, 4, 5])
t = np.array([1, 1, 3, 2, 5])

sum( p == t)

# 배열에서 같은 것의 개수를 반환

3

In [29]:
def predict(network, x):
    w1, w2, w3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, w1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, w2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, w3) + b3
    y = softmax(a3)

    return y

x, t = get_data()
x = x.reshape(-1,784)
print(x[0].shape)
network = init_network()
print(len(x))
batch_size = 100 # 배치 크기
accuracy_cnt = 0

for i in range(0, len(x), batch_size): # 100개씩 묶어서 100번 돌림
    x_batch = x[i:i+batch_size]
    print(f'x_batch: {x_batch.shape}')
    y_batch = predict(network, x_batch)
    # print(y_batch.shape)
    p = np.argmax(y_batch, axis=1) # predict를 통해 나온 100 * 10 에서 행에서 가장 값이 큰 인덱스 반환
    print(f'y_batch: {y_batch.shape}')
    print(p)
    print(f't: {t[i:i+batch_size]}')
    accuracy_cnt += np.sum(p == t[i:i+batch_size]) # t에서 100개씩 짤라 p와 비교하여 맞은 개수를 갱신

print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

(784,)
10000
x_batch: (100, 784)
y_batch: (100, 10)
[7 2 1 0 4 1 4 9 6 9 0 6 9 0 1 5 9 7 3 4 9 6 6 5 4 0 7 4 0 1 3 1 3 6 7 2 7
 1 2 1 1 7 4 2 3 5 1 2 4 4 6 3 5 5 6 0 4 1 9 7 7 8 9 3 7 4 6 4 3 0 7 0 2 9
 1 7 3 2 9 7 7 6 2 7 8 4 7 3 6 1 3 6 4 3 1 4 1 7 6 9]
t: [7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4 9 6 6 5 4 0 7 4 0 1 3 1 3 4 7 2 7
 1 2 1 1 7 4 2 3 5 1 2 4 4 6 3 5 5 6 0 4 1 9 5 7 8 9 3 7 4 6 4 3 0 7 0 2 9
 1 7 3 2 9 7 7 6 2 7 8 4 7 3 6 1 3 6 9 3 1 4 1 7 6 9]
x_batch: (100, 784)
y_batch: (100, 10)
[6 0 5 4 9 9 2 1 9 4 8 1 3 9 7 4 4 4 9 8 5 8 7 6 4 9 0 5 8 5 6 6 5 7 8 1 0
 1 6 4 6 7 3 1 9 1 8 2 0 9 9 9 5 5 1 5 6 0 3 4 4 6 5 4 6 5 4 5 1 4 4 7 2 3
 2 7 1 8 1 8 1 8 5 0 8 9 2 5 0 1 1 1 0 9 0 8 1 6 4 2]
t: [6 0 5 4 9 9 2 1 9 4 8 7 3 9 7 4 4 4 9 2 5 4 7 6 7 9 0 5 8 5 6 6 5 7 8 1 0
 1 6 4 6 7 3 1 7 1 8 2 0 2 9 9 5 5 1 5 6 0 3 4 4 6 5 4 6 5 4 5 1 4 4 7 2 3
 2 7 1 8 1 8 1 8 5 0 8 9 2 5 0 1 1 1 0 9 0 3 1 6 4 2]
x_batch: (100, 784)
y_batch: (100, 10)
[3 6 1 1 1 3 9 5 2 9 4 7 9 3 9 0 3 5 5 5 7 2 2 7

C:\Users\junun\AppData\Local\Temp\ipykernel_16756\3098911386.py:19: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))
